apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-config-claim
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeName: foundrydata
  resources:
    requests:
      storage: "{{ .Values.configsize }}"
